import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: "320px",
      sm: "480px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
      "3xl": "1920px",
      "4xl": "2560px",
      "5xl": "3840px",
    },
    extend: {
      maxWidth: {
        "container-xl": "1280px",
        "container-2xl": "1440px",
        "container-3xl": "1760px",
        "container-4xl": "2200px",
        "container-5xl": "3200px",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "bg-page": "var(--bg-page)",
        "bg-card": "var(--bg-card)",
        "bg-chip": "var(--bg-chip)",
        "bg-hover": "var(--bg-hover)",
        divider: "var(--divider)",
        "text-primary": "var(--text-primary)",
        "text-muted": "var(--text-muted)",
        "accent-contrast": "var(--accent-contrast)",
        "value-text": "var(--value-text)",
        "trend-up": "var(--trend-up)",
        "trend-down": "var(--trend-down)",
        live: "var(--live)",
        ink: {
          950: "var(--ink-950)",
          900: "var(--ink-900)",
          800: "var(--ink-800)",
          700: "var(--ink-700)",
          850: "#121724",
          600: "#313E56",
        },
        surface: {
          50: "#f8fafc",
          100: "#f1f5f9",
          800: "var(--ink-800)",
          900: "var(--ink-900)",
          950: "var(--ink-950)",
        },
        brand: {
          50: "#fffbeb",
          100: "#fef3c7",
          400: "var(--amber-400)",
          500: "var(--amber-500)",
          600: "#d97706",
          700: "#b45309",
        },
        pitch: {
          50: "#ecfdf5",
          100: "#d1fae5",
          400: "#34d399",
          500: "var(--green-500)",
          600: "#059669",
          700: "#047857",
        },
        accent: {
          DEFAULT: "var(--accent)",
          contrast: "var(--accent-contrast)",
          50: "#eff6ff",
          100: "#dbeafe",
          500: "#3b82f6",
          600: "#2563eb",
        },
      },
      borderRadius: {
        card: "var(--card-radius)",
        chip: "var(--chip-radius)",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "var(--font-sans)", "system-ui", "sans-serif"],
        editorial: ["Georgia", "Cambria", "Times New Roman", "serif"],
      },
    },
  },
  plugins: [],
};
export default config;
